# .github/workflows/test.yml

name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
          # 必要なライブラリがあれば指定

    - name: Run tests
      run: python test_script.py  # テストスクリプトのファイル名を適切なものに変更

