#!/bin/bash

# プログラムのパス
PROGRAM_PATH="./plus"

# テストケース1: 正常な入力
echo -e "10\n20\n30\n" | $PROGRAM_PATH

# テストケース2: 不正な入力を含む
echo -e "a\n20\n30\n" | $PROGRAM_PATH

# テストケース3: 空の入力
echo -e "" | $PROGRAM_PATH

