#!/bin/bash

# テスト用のデータを含むファイルを作成
echo -e "5\n10\n15\n" > test_input.txt

# テストスクリプトの実行
seq 5 | ./plus < test_input.txt > test_output.txt

# 期待される出力と実際の出力を比較
expected_output=$(cat << EOF
Total: 30.0
Average: 10.0
Maximum: 15.0
Minimum: 5.0
Variance: 16.666666666666668
Even Numbers: [10.0]
Odd Numbers: [5.0, 15.0]
Positive Numbers: [5.0, 10.0, 15.0]
Negative Numbers: []
EOF
)

actual_output=$(cat test_output.txt)

if [ "$expected_output" == "$actual_output" ]; then
    echo "Test Passed"
else
    echo "Test Failed"
fi

# 一時ファイルのクリーンアップ
rm test_input.txt test_output.txt

